sudo: false
language: node_js
node_js:
- '4.2'
- '4.1'
- '4.0'
before_script:
- echo -e '{"key":"'$key'","secret":"'$secret'","dist":"'$dist'"}' > aws.json
env:
  global:
  - secure: vaaMJ4lKVihhnPlRQ0/qvBlcxFPadvQbPLhKgrOVblLgr6FGZiIH4TrQG9gkQbMJZENgY0nJlGgSz0hheF0qmJS7MtZajSuw1ELAzi2MRkUgHkJ/PoSC9QqIRnt+yIaXV69F4mqJ7l7aTw58abtkhcl5zP/DQ+y+Pun2bDQAp0c=
  - secure: vWob9i8whgY91L8LGycjmFFJCoLeqZ8qLQ5+UowsRO7UWzY42B9Nhs8OCHUlA1NpIBBr6lQbgSW75oGyGpKODv6TJ6t1xOEr38nGOJsmYvRhALva9bArSyj1r1SZktElxOQP38LMIU5KwziuBytlLixRLz+Bzz+mT5gOk/n47K4=
  - secure: bI6EWog1teHZmfS66xSypLKaoA+oVpr1KPKfi5GDlhvdhztAX4wdLg6jGXYEjTE6FmeGdhSonXSsZhBWdKILIvePqcwVnh90S3UMyAP6AM6wVPpISODsBMh7xw/2f8i1jSOKDG9meqbgASGb/uHMbak3U5vSFf/XxE7UL65yXYc=
deploy:
- provider: s3
  access_key_id:
    secure: yYc+88r+WOCzcnNe6rqMTPHv0+mCLz4FwMm5amj4k0K442084UQ7aKmLJ3VD6XRavnL3g2ThjON54han0z+TaDUrwzJAYSwYBOesN4d4v4ZARfzwKJhz4+jVU/zW+n2nxvwrP5KJLt3ghEZMRY+0xKPORev02XPfeyPCgrgHtRA=    
  secret_access_key:
    secure: ZzTpKHfJOQUF5IVnFL7Ki6PkUuEntN7LQ37Uvfp87Iol6aCtsXmKi5rLN0SQzQ9OvDaNGClzmPt5hLT2pFseuHudiQyU/mowI/92Chzyd9waOxikpxX6iflvbK7Tc/VENhwB/xdRdSnXACKfYwe+NHsladExnaizFOzUoKkoDLM=
  bucket: matchstickjs-com
  local_dir: build
  skip_cleanup: true
  on:
    repo: edj-boston/matchstickjs-com
    branch: master
- provider: s3
  access_key_id:
    secure: C7vhBhONxjdxWuO/vmxYZ41BWNl3e8EA9DRZlhhSLy88BCeqqqRIGEBRjdl6esUeOP8xlfQlH11YFcpKYy8Dq6/ERBLWdHjAA4FeeR/Z3eNWGdBao1pQCt35U+kMXZXqW+OGYCB9fPj3qtqT4vj3y4KZW/IWYvMdR4LQ8fUUw5I=
  secret_access_key:
    secure: XvYLb75edykthdScHIY3qtOQqmy163IrGNbCLNagBgwPp1hUDuu0LdxcNheJ02exhgskdXThlYRt5+HYmk2g0pGYsNnAOnWpPeNRXm7GHZe0GGXhA+QLCV19oO4f0buU/8TpxuolZBcp05rT7DlRE2qDuhoNjJzjD6RezFyQOIA=    
  bucket: stage-matchstickjs-com
  local_dir: build
  skip_cleanup: true
  on:
    repo: edj-boston/matchstickjs-com
    branch: develop